export const GET_POKEMONS = 'GET_POKEMONS';
export const SET_POKEMON_DETAIL = 'SET_POKEMON_DETAIL';
export const CLEAN_POKEMON_DETAIL = 'CLEAN_POKEMON_DETAIL';
export const SET_CURRENT_POKEMON = 'SET_CURRENT_POKEMON';
export const CLEAN_CURRENT_POKEMON = 'CLEAN_CURRENT_POKEMON';
